{% set name = "anaconda-registration" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic
  script: |
    mkdir %PREFIX%\condarc.d  # [win]
    mkdir $PREFIX/condarc.d   # [not win]
    copy %RECIPE_DIR%\registration.yml %PREFIX%\condarc.d\  # [win]
    cp $RECIPE_DIR/registration.yml $PREFIX/condarc.d/      # [not win]

requirements:
  run:
    - anaconda-anon-usage >=0.7.4
    - anaconda-auth >=0.9.1
    - conda-anaconda-telemetry >=0.3.0

test:
  imports:
    - conda_anaconda_telemetry
    - anaconda_anon_usage
    - anaconda_auth
  commands:
    - if not exist %PREFIX%\condarc.d\registration.yml exit 1  # [win]
    - test -f $PREFIX/condarc.d/registration.yml               # [not win]

about:
  home: https://github.com/AnacondaRecipes/anaconda-registration-feedstock
  summary: A metapackage to facilitate conda registration
  description: |
    A metapackage to ensure that the dependencies for conda registration are installed
    and anaconda-anon-usage telemetry is enabled. This provides a convenient method to
    ensure that a conda client is properly configured for registration.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/AnacondaRecipes/anaconda-registration-feedstock
  doc_url: https://github.com/AnacondaRecipes/anaconda-registration-feedstock

extra:
  recipe-maintainers:
    - mcg1969
